(******************************************************************************

  %name: nwcalls.h %
  %version: 4 %
  %date_modified: Tue Jul 29 15:44:05 1997 %
  $Copyright:

  Copyright (c) 1989-1995 Novell, Inc.  All Rights Reserved.                      

  THIS WORK IS  SUBJECT  TO  U.S.  AND  INTERNATIONAL  COPYRIGHT  LAWS  AND
  TREATIES.   NO  PART  OF  THIS  WORK MAY BE  USED,  PRACTICED,  PERFORMED
  COPIED, DISTRIBUTED, REVISED, MODIFIED, TRANSLATED,  ABRIDGED, CONDENSED,
  EXPANDED,  COLLECTED,  COMPILED,  LINKED,  RECAST, TRANSFORMED OR ADAPTED
  WITHOUT THE PRIOR WRITTEN CONSENT OF NOVELL, INC. ANY USE OR EXPLOITATION
  OF THIS WORK WITHOUT AUTHORIZATION COULD SUBJECT THE PERPETRATOR TO
  CRIMINAL AND CIVIL LIABILITY.$

 *****************************************************************************)


{$IFNDEF  NWCALLS_H }
    {$DEFINE NWCALLS_H}
    {$IFNDEF  NWAPIDEF_H }
        {$I nwapidef.inc}
    {$ENDIF}
    {$IFNDEF  NWCALDEF_H }
        {$I nwcaldef.inc}
    {$ENDIF}
    {$IFNDEF  NWALIAS_H }
        {$I nwalias.inc}
    {$ENDIF}
    {$IFNDEF  NOAFP_INC }
        {$I nwafp.inc}
    {$ENDIF}
    {$IFNDEF  NOBINDRY_INC }
        {$I nwbindry.inc}
    {$ENDIF}
    {$IFNDEF  NOCONNECT_INC }
        {$I nwconnec.inc}
    {$ENDIF}
    {$IFNDEF  NODEL_INC }
        {$I nwdel.inc}
    {$ENDIF}
    {$IFNDEF  NODENTRY_INC }
        {$I nwdentry.inc}
    {$ENDIF}
    {$IFNDEF  NODIRECTORY_INC }
        {$I nwdirect.inc}
    {$ENDIF}
    {$IFNDEF  NODPATH_INC }
        {$I nwdpath.inc}
    {$ENDIF}
    {$IFNDEF  NOEA_INC }
        {$I nwea.inc}
    {$ENDIF}
    {$IFNDEF  NOERROR_INC }
        {$I nwerror.inc}
    {$ENDIF}
    {$IFNDEF  NOFILES_INC }
        {$I nwfile.inc}
    {$ENDIF}
    {$IFNDEF  NOMISC_INC }
        {$I nwmisc.inc}
    {$ENDIF}
    {$IFNDEF  NOMESSAGES_INC }
        {$I nwmsg.inc}
    {$ENDIF}
    {$IFNDEF  NONAMSPC_INC }
        {$I nwnamspc.inc}
    {$ENDIF}
    {$IFNDEF  NOPRINT_INC }
        {$I nwprint.inc}
    {$ENDIF}
    {$IFNDEF  NOQUEUE_INC }
        {$I nwqms.inc}
    {$ENDIF}
    {$IFNDEF  NOSERVER_INC }
        {$I nwserver.inc}
    {$ENDIF}
    {$IFNDEF  NOSYNC_INC }
        {$I nwsync.inc}
    {$ENDIF}
    {$IFNDEF  NONTTS_INC }
        {$I nwtts.inc}
    {$ENDIF}
    {$IFNDEF  NOVOL_INC }
        {$I nwvol.inc}
    {$ENDIF}
    {$IFNDEF  NOACCT_INC }
        {$I nwacct.inc}
    {$ENDIF}
    {$IFNDEF  NOFSE_INC }
        {$I nwfse.inc}
    {$ENDIF}
    {$IFNDEF  NOMIGRATE_INC }
        {$I nwmigrat.inc}
    {$ENDIF}
    {$IFNDEF  NOSM_INC }
        {$I nwsm.inc}
    {$ENDIF}
{$ENDIF}

