unit NWCErrTxt;

interface

uses
  Windows, Classes, SysUtils, NetWin32;

function NWCErrorMessage(ErrorCode: Integer): String;
function SysAndNWCErrorMessage(ErrorCode: Integer): String;
function CheckNWCError(Operation: string; Res: DWORD): string;

implementation

{$IFDEF VER90}
const
{$ELSE}
resourcestring
{$ENDIF}

(* -301 to -399 are returned by the directory services client library *)

   sERR_NOT_ENOUGH_MEMORY = 'NOT_ENOUGH_MEMORY';
   sERR_BAD_KEY = 'BAD_KEY';
   sERR_BAD_CONTEXT = 'BAD_CONTEXT';
   sERR_BUFFER_FULL = 'BUFFER_FULL';
   sERR_LIST_EMPTY = 'LIST_EMPTY';
   sERR_BAD_SYNTAX = 'BAD_SYNTAX';
   sERR_BUFFER_EMPTY = 'BUFFER_EMPTY';
   sERR_BAD_VERB = 'BAD_VERB';
   sERR_EXPECTED_IDENTIFIER = 'EXPECTED_IDENTIFIER';
   sERR_EXPECTED_EQUALS = 'EXPECTED_EQUALS';
   sERR_ATTR_TYPE_EXPECTED = 'ATTR_TYPE_EXPECTED';
   sERR_ATTR_TYPE_NOT_EXPECTED = 'ATTR_TYPE_NOT_EXPECTED';
   sERR_FILTER_TREE_EMPTY = 'FILTER_TREE_EMPTY';
   sERR_INVALID_OBJECT_NAME = 'INVALID_OBJECT_NAME';
   sERR_EXPECTED_RDN_DELIMITER = 'EXPECTED_RDN_DELIMITER';
   sERR_TOO_MANY_TOKENS = 'TOO_MANY_TOKENS';
   sERR_INCONSISTENT_MULTIAVA = 'INCONSISTENT_MULTIAVA';
   sERR_COUNTRY_NAME_TOO_LONG = 'COUNTRY_NAME_TOO_LONG';
   sERR_SYSTEM_ERROR = 'SYSTEM_ERROR';
   sERR_CANT_ADD_ROOT = 'CANT_ADD_ROOT';
   sERR_UNABLE_TO_ATTACH = 'UNABLE_TO_ATTACH';
   sERR_INVALID_HANDLE = 'INVALID_HANDLE';
   sERR_BUFFER_ZERO_LENGTH = 'BUFFER_ZERO_LENGTH';
   sERR_INVALID_REPLICA_TYPE = 'INVALID_REPLICA_TYPE';
   sERR_INVALID_ATTR_SYNTAX = 'INVALID_ATTR_SYNTAX';
   sERR_INVALID_FILTER_SYNTAX = 'INVALID_FILTER_SYNTAX';
   sERR_CONTEXT_CREATION = 'CONTEXT_CREATION';
   sERR_INVALID_UNION_TAG = 'INVALID_UNION_TAG';
   sERR_INVALID_SERVER_RESPONSE = 'INVALID_SERVER_RESPONSE';
   sERR_NULL_POINTER = 'NULL_POINTER';
   sERR_NO_SERVER_FOUND = 'NO_SERVER_FOUND';
   sERR_NO_CONNECTION = 'NO_CONNECTION';
   sERR_RDN_TOO_LONG = 'RDN_TOO_LONG';
   sERR_DUPLICATE_TYPE = 'DUPLICATE_TYPE';
   sERR_DATA_STORE_FAILURE = 'DATA_STORE_FAILURE';
   sERR_NOT_LOGGED_IN = 'NOT_LOGGED_IN';
   sERR_INVALID_PASSWORD_CHARS = 'INVALID_PASSWORD_CHARS';
   sERR_FAILED_SERVER_AUTHENT = 'FAILED_SERVER_AUTHENT';
   sERR_TRANSPORT = 'TRANSPORT';
   sERR_NO_SUCH_SYNTAX = 'NO_SUCH_SYNTAX';
   sERR_INVALID_DS_NAME = 'INVALID_DS_NAME';
   sERR_ATTR_NAME_TOO_LONG = 'ATTR_NAME_TOO_LONG';
   sERR_INVALID_TDS = 'INVALID_TDS';
   sERR_INVALID_DS_VERSION = 'INVALID_DS_VERSION';
   sERR_UNICODE_TRANSLATION = 'UNICODE_TRANSLATION';
   sERR_SCHEMA_NAME_TOO_LONG = 'SCHEMA_NAME_TOO_LONG';
   sERR_UNICODE_FILE_NOT_FOUND = 'UNICODE_FILE_NOT_FOUND';
   sERR_UNICODE_ALREADY_LOADED = 'UNICODE_ALREADY_LOADED';
   sERR_NOT_CONTEXT_OWNER = 'NOT_CONTEXT_OWNER';
   sERR_ATTEMPT_TO_AUTHENTICATE_0 = 'ATTEMPT_TO_AUTHENTICATE_0';
   sERR_NO_WRITABLE_REPLICAS = 'NO_WRITABLE_REPLICAS';
   sERR_DN_TOO_LONG = 'DN_TOO_LONG';
   sERR_RENAME_NOT_ALLOWED = 'RENAME_NOT_ALLOWED';

(* -601 to -699 are returned by the directory services agent in the server *)

   sERR_NO_SUCH_ENTRY = 'NO_SUCH_ENTRY';
   sERR_NO_SUCH_VALUE = 'NO_SUCH_VALUE';
   sERR_NO_SUCH_ATTRIBUTE = 'NO_SUCH_ATTRIBUTE';
   sERR_NO_SUCH_CLASS = 'NO_SUCH_CLASS';
   sERR_NO_SUCH_PARTITION = 'NO_SUCH_PARTITION';
   sERR_ENTRY_ALREADY_EXISTS = 'ENTRY_ALREADY_EXISTS';
   sERR_NOT_EFFECTIVE_CLASS = 'NOT_EFFECTIVE_CLASS';
   sERR_ILLEGAL_ATTRIBUTE = 'ILLEGAL_ATTRIBUTE';
   sERR_MISSING_MANDATORY = 'MISSING_MANDATORY';
   sERR_ILLEGAL_DS_NAME = 'ILLEGAL_DS_NAME';
   sERR_ILLEGAL_CONTAINMENT = 'ILLEGAL_CONTAINMENT';
   sERR_CANT_HAVE_MULTIPLE_VALUES = 'CANT_HAVE_MULTIPLE_VALUES';
   sERR_SYNTAX_VIOLATION = 'SYNTAX_VIOLATION';
   sERR_DUPLICATE_VALUE = 'DUPLICATE_VALUE';
   sERR_ATTRIBUTE_ALREADY_EXISTS = 'ATTRIBUTE_ALREADY_EXISTS';
   sERR_MAXIMUM_ENTRIES_EXIST = 'MAXIMUM_ENTRIES_EXIST';
   sERR_DATABASE_FORMAT = 'DATABASE_FORMAT';
   sERR_INCONSISTENT_DATABASE = 'INCONSISTENT_DATABASE';
   sERR_INVALID_COMPARISON = 'INVALID_COMPARISON';
   sERR_COMPARISON_FAILED = 'COMPARISON_FAILED';
   sERR_TRANSACTIONS_DISABLED = 'TRANSACTIONS_DISABLED';
   sERR_INVALID_TRANSPORT = 'INVALID_TRANSPORT';
   sERR_SYNTAX_INVALID_IN_NAME = 'SYNTAX_INVALID_IN_NAME';
   sERR_REPLICA_ALREADY_EXISTS = 'REPLICA_ALREADY_EXISTS';
   sERR_TRANSPORT_FAILURE = 'TRANSPORT_FAILURE';
   sERR_ALL_REFERRALS_FAILED = 'ALL_REFERRALS_FAILED';
   sERR_CANT_REMOVE_NAMING_VALUE = 'CANT_REMOVE_NAMING_VALUE';
   sERR_OBJECT_CLASS_VIOLATION = 'OBJECT_CLASS_VIOLATION';
   sERR_ENTRY_IS_NOT_LEAF = 'ENTRY_IS_NOT_LEAF';
   sERR_DIFFERENT_TREE = 'DIFFERENT_TREE';
   sERR_ILLEGAL_REPLICA_TYPE = 'ILLEGAL_REPLICA_TYPE';
   sERR_SYSTEM_FAILURE = 'SYSTEM_FAILURE';
   sERR_INVALID_ENTRY_FOR_ROOT = 'INVALID_ENTRY_FOR_ROOT';
   sERR_NO_REFERRALS = 'NO_REFERRALS';
   sERR_REMOTE_FAILURE = 'REMOTE_FAILURE';
   sERR_UNREACHABLE_SERVER = 'UNREACHABLE_SERVER';
   sERR_PREVIOUS_MOVE_IN_PROGRESS = 'PREVIOUS_MOVE_IN_PROGRESS';
   sERR_NO_CHARACTER_MAPPING = 'NO_CHARACTER_MAPPING';
   sERR_INCOMPLETE_AUTHENTICATION = 'INCOMPLETE_AUTHENTICATION';
   sERR_INVALID_CERTIFICATE = 'INVALID_CERTIFICATE';
   sERR_INVALID_REQUEST = 'INVALID_REQUEST';
   sERR_INVALID_ITERATION = 'INVALID_ITERATION';
   sERR_SCHEMA_IS_NONREMOVABLE = 'SCHEMA_IS_NONREMOVABLE';
   sERR_SCHEMA_IS_IN_USE = 'SCHEMA_IS_IN_USE';
   sERR_CLASS_ALREADY_EXISTS = 'CLASS_ALREADY_EXISTS';
   sERR_BAD_NAMING_ATTRIBUTES = 'BAD_NAMING_ATTRIBUTES';
   sERR_NOT_ROOT_PARTITION = 'NOT_ROOT_PARTITION';
   sERR_INSUFFICIENT_STACK = 'INSUFFICIENT_STACK';
   sERR_INSUFFICIENT_BUFFER = 'INSUFFICIENT_BUFFER';
   sERR_AMBIGUOUS_CONTAINMENT = 'AMBIGUOUS_CONTAINMENT';
   sERR_AMBIGUOUS_NAMING = 'AMBIGUOUS_NAMING';
   sERR_DUPLICATE_MANDATORY = 'DUPLICATE_MANDATORY';
   sERR_DUPLICATE_OPTIONAL = 'DUPLICATE_OPTIONAL';
   sERR_PARTITION_BUSY = 'PARTITION_BUSY';
   sERR_MULTIPLE_REPLICAS = 'MULTIPLE_REPLICAS';
   sERR_CRUCIAL_REPLICA = 'CRUCIAL_REPLICA';
   sERR_SCHEMA_SYNC_IN_PROGRESS = 'SCHEMA_SYNC_IN_PROGRESS';
   sERR_SKULK_IN_PROGRESS = 'SKULK_IN_PROGRESS';
   sERR_TIME_NOT_SYNCHRONIZED = 'TIME_NOT_SYNCHRONIZED';
   sERR_RECORD_IN_USE = 'RECORD_IN_USE';
   sERR_DS_VOLUME_NOT_MOUNTED = 'DS_VOLUME_NOT_MOUNTED';
   sERR_DS_VOLUME_IO_FAILURE = 'DS_VOLUME_IO_FAILURE';
   sERR_DS_LOCKED = 'DS_LOCKED';
   sERR_OLD_EPOCH = 'OLD_EPOCH';
   sERR_NEW_EPOCH = 'NEW_EPOCH';
   sERR_INCOMPATIBLE_DS_VERSION = 'INCOMPATIBLE_DS_VERSION';
   sERR_PARTITION_ROOT = 'PARTITION_ROOT';
   sERR_ENTRY_NOT_CONTAINER = 'ENTRY_NOT_CONTAINER';
   sERR_FAILED_AUTHENTICATION = 'FAILED_AUTHENTICATION';
   sERR_INVALID_CONTEXT = 'INVALID_CONTEXT';
   sERR_NO_SUCH_PARENT = 'NO_SUCH_PARENT';
   sERR_NO_ACCESS = 'NO_ACCESS';
   sERR_REPLICA_NOT_ON = 'REPLICA_NOT_ON';
   sERR_INVALID_NAME_SERVICE = 'INVALID_NAME_SERVICE';
   sERR_INVALID_TASK = 'INVALID_TASK';
   sERR_INVALID_CONN_HANDLE = 'INVALID_CONN_HANDLE';
   sERR_INVALID_IDENTITY = 'INVALID_IDENTITY';
   sERR_DUPLICATE_ACL = 'DUPLICATE_ACL';
   sERR_PARTITION_ALREADY_EXISTS = 'PARTITION_ALREADY_EXISTS';
   sERR_TRANSPORT_MODIFIED = 'TRANSPORT_MODIFIED';
   sERR_ALIAS_OF_AN_ALIAS = 'ALIAS_OF_AN_ALIAS';
   sERR_AUDITING_FAILED = 'AUDITING_FAILED';
   sERR_INVALID_API_VERSION = 'INVALID_API_VERSION';
   sERR_SECURE_NCP_VIOLATION = 'SECURE_NCP_VIOLATION';
   sERR_MOVE_IN_PROGRESS = 'MOVE_IN_PROGRESS';
   sERR_NOT_LEAF_PARTITION = 'NOT_LEAF_PARTITION';
   sERR_CANNOT_ABORT = 'CANNOT_ABORT';
   sERR_CACHE_OVERFLOW = 'CACHE_OVERFLOW';
   sERR_INVALID_SUBORDINATE_COUNT = 'INVALID_SUBORDINATE_COUNT';
   sERR_INVALID_RDN = 'INVALID_RDN';
   sERR_MOD_TIME_NOT_CURRENT = 'MOD_TIME_NOT_CURRENT';
   sERR_INCORRECT_BASE_CLASS = 'INCORRECT_BASE_CLASS';
   sERR_MISSING_REFERENCE = 'MISSING_REFERENCE';
   sERR_LOST_ENTRY = 'LOST_ENTRY';
   sERR_AGENT_ALREADY_REGISTERED = 'AGENT_ALREADY_REGISTERED';
   sERR_DS_LOADER_BUSY = 'DS_LOADER_BUSY';
   sERR_DS_CANNOT_RELOAD = 'DS_CANNOT_RELOAD';
   sERR_REPLICA_IN_SKULK = 'REPLICA_IN_SKULK';
   sERR_FATAL = 'FATAL';
   sERR_OBSOLETE_API = 'OBSOLETE_API';
   sERR_SYNCHRONIZATION_DISABLED = 'SYNCHRONIZATION_DISABLED';
   sERR_INVALID_PARAMETER = 'INVALID_PARAMETER';
   sERR_DUPLICATE_TEMPLATE = 'DUPLICATE_TEMPLATE';
   sERR_NO_MASTER_REPLICA = 'NO_MASTER_REPLICA';
   sERR_DUPLICATE_CONTAINMENT = 'DUPLICATE_CONTAINMENT';
   sERR_NOT_SIBLING = 'NOT_SIBLING';
   sERR_INVALID_SIGNATURE = 'INVALID_SIGNATURE';
   sERR_INVALID_RESPONSE = 'INVALID_RESPONSE';
   sERR_INSUFFICIENT_SOCKETS = 'INSUFFICIENT_SOCKETS';
   sERR_DATABASE_READ_FAIL = 'DATABASE_READ_FAIL';
   sERR_INVALID_CODE_PAGE = 'INVALID_CODE_PAGE';
   sERR_INVALID_ESCAPE_CHAR = 'INVALID_ESCAPE_CHAR';
   sERR_INVALID_DELIMITERS = 'INVALID_DELIMITERS';
   sERR_NOT_IMPLEMENTED = 'NOT_IMPLEMENTED';
   sERR_CHECKSUM_FAILURE = 'CHECKSUM_FAILURE';
   sERR_CHECKSUMMING_NOT_SUPPORTED = 'CHECKSUMMING_NOT_SUPPORTED';
   sERR_CRC_FAILURE = 'CRC_FAILURE';
   sNWCError = 'Operation: %s'#13#10'Net Error code: %d.'#13#10'"%s"';

function NWCErrorMessage(ErrorCode: Integer): String;
begin
  case ErrorCode of

     (* -301 to -399 are returned by the directory services client library *)

     ERR_NOT_ENOUGH_MEMORY: Result := sERR_NOT_ENOUGH_MEMORY;
     ERR_BAD_KEY: Result := sERR_BAD_KEY;
     ERR_BAD_CONTEXT: Result := sERR_BAD_CONTEXT;
     ERR_BUFFER_FULL: Result := sERR_BUFFER_FULL;
     ERR_LIST_EMPTY: Result := sERR_LIST_EMPTY;
     ERR_BAD_SYNTAX: Result := sERR_BAD_SYNTAX;
     ERR_BUFFER_EMPTY: Result := sERR_BUFFER_EMPTY;
     ERR_BAD_VERB: Result := sERR_BAD_VERB;
     ERR_EXPECTED_IDENTIFIER: Result := sERR_EXPECTED_IDENTIFIER;
     ERR_EXPECTED_EQUALS: Result := sERR_EXPECTED_EQUALS;
     ERR_ATTR_TYPE_EXPECTED: Result := sERR_ATTR_TYPE_EXPECTED;
     ERR_ATTR_TYPE_NOT_EXPECTED: Result := sERR_ATTR_TYPE_NOT_EXPECTED;
     ERR_FILTER_TREE_EMPTY: Result := sERR_FILTER_TREE_EMPTY;
     ERR_INVALID_OBJECT_NAME: Result := sERR_INVALID_OBJECT_NAME;
     ERR_EXPECTED_RDN_DELIMITER: Result := sERR_EXPECTED_RDN_DELIMITER;
     ERR_TOO_MANY_TOKENS: Result := sERR_TOO_MANY_TOKENS;
     ERR_INCONSISTENT_MULTIAVA: Result := sERR_INCONSISTENT_MULTIAVA;
     ERR_COUNTRY_NAME_TOO_LONG: Result := sERR_COUNTRY_NAME_TOO_LONG;
     ERR_SYSTEM_ERROR: Result := sERR_SYSTEM_ERROR;
     ERR_CANT_ADD_ROOT: Result := sERR_CANT_ADD_ROOT;
     ERR_UNABLE_TO_ATTACH: Result := sERR_UNABLE_TO_ATTACH;
     ERR_INVALID_HANDLE: Result := sERR_INVALID_HANDLE;
     ERR_BUFFER_ZERO_LENGTH: Result := sERR_BUFFER_ZERO_LENGTH;
     ERR_INVALID_REPLICA_TYPE: Result := sERR_INVALID_REPLICA_TYPE;
     ERR_INVALID_ATTR_SYNTAX: Result := sERR_INVALID_ATTR_SYNTAX;
     ERR_INVALID_FILTER_SYNTAX: Result := sERR_INVALID_FILTER_SYNTAX;
     ERR_CONTEXT_CREATION: Result := sERR_CONTEXT_CREATION;
     ERR_INVALID_UNION_TAG: Result := sERR_INVALID_UNION_TAG;
     ERR_INVALID_SERVER_RESPONSE: Result := sERR_INVALID_SERVER_RESPONSE;
     ERR_NULL_POINTER: Result := sERR_NULL_POINTER;
     ERR_NO_SERVER_FOUND: Result := sERR_NO_SERVER_FOUND;
     ERR_NO_CONNECTION: Result := sERR_NO_CONNECTION;
     ERR_RDN_TOO_LONG: Result := sERR_RDN_TOO_LONG;
     ERR_DUPLICATE_TYPE: Result := sERR_DUPLICATE_TYPE;
     ERR_DATA_STORE_FAILURE: Result := sERR_DATA_STORE_FAILURE;
     ERR_NOT_LOGGED_IN: Result := sERR_NOT_LOGGED_IN;
     ERR_INVALID_PASSWORD_CHARS: Result := sERR_INVALID_PASSWORD_CHARS;
     ERR_FAILED_SERVER_AUTHENT: Result := sERR_FAILED_SERVER_AUTHENT;
     ERR_TRANSPORT: Result := sERR_TRANSPORT;
     ERR_NO_SUCH_SYNTAX: Result := sERR_NO_SUCH_SYNTAX;
     ERR_INVALID_DS_NAME: Result := sERR_INVALID_DS_NAME;
     ERR_ATTR_NAME_TOO_LONG: Result := sERR_ATTR_NAME_TOO_LONG;
     ERR_INVALID_TDS: Result := sERR_INVALID_TDS;
     ERR_INVALID_DS_VERSION: Result := sERR_INVALID_DS_VERSION;
     ERR_UNICODE_TRANSLATION: Result := sERR_UNICODE_TRANSLATION;
     ERR_SCHEMA_NAME_TOO_LONG: Result := sERR_SCHEMA_NAME_TOO_LONG;
     ERR_UNICODE_FILE_NOT_FOUND: Result := sERR_UNICODE_FILE_NOT_FOUND;
     ERR_UNICODE_ALREADY_LOADED: Result := sERR_UNICODE_ALREADY_LOADED;
     ERR_NOT_CONTEXT_OWNER: Result := sERR_NOT_CONTEXT_OWNER;
     ERR_ATTEMPT_TO_AUTHENTICATE_0: Result := sERR_ATTEMPT_TO_AUTHENTICATE_0;
     ERR_NO_WRITABLE_REPLICAS: Result := sERR_NO_WRITABLE_REPLICAS;
     ERR_DN_TOO_LONG: Result := sERR_DN_TOO_LONG;
     ERR_RENAME_NOT_ALLOWED: Result := sERR_RENAME_NOT_ALLOWED;

     (* -601 to -699 are returned by the directory services agent in the server *)

     ERR_NO_SUCH_ENTRY: Result := sERR_NO_SUCH_ENTRY;
     ERR_NO_SUCH_VALUE: Result := sERR_NO_SUCH_VALUE;
     ERR_NO_SUCH_ATTRIBUTE: Result := sERR_NO_SUCH_ATTRIBUTE;
     ERR_NO_SUCH_CLASS: Result := sERR_NO_SUCH_CLASS;
     ERR_NO_SUCH_PARTITION: Result := sERR_NO_SUCH_PARTITION;
     ERR_ENTRY_ALREADY_EXISTS: Result := sERR_ENTRY_ALREADY_EXISTS;
     ERR_NOT_EFFECTIVE_CLASS: Result := sERR_NOT_EFFECTIVE_CLASS;
     ERR_ILLEGAL_ATTRIBUTE: Result := sERR_ILLEGAL_ATTRIBUTE;
     ERR_MISSING_MANDATORY: Result := sERR_MISSING_MANDATORY;
     ERR_ILLEGAL_DS_NAME: Result := sERR_ILLEGAL_DS_NAME;
     ERR_ILLEGAL_CONTAINMENT: Result := sERR_ILLEGAL_CONTAINMENT;
     ERR_CANT_HAVE_MULTIPLE_VALUES: Result := sERR_CANT_HAVE_MULTIPLE_VALUES;
     ERR_SYNTAX_VIOLATION: Result := sERR_SYNTAX_VIOLATION;
     ERR_DUPLICATE_VALUE: Result := sERR_DUPLICATE_VALUE;
     ERR_ATTRIBUTE_ALREADY_EXISTS: Result := sERR_ATTRIBUTE_ALREADY_EXISTS;
     ERR_MAXIMUM_ENTRIES_EXIST: Result := sERR_MAXIMUM_ENTRIES_EXIST;
     ERR_DATABASE_FORMAT: Result := sERR_DATABASE_FORMAT;
     ERR_INCONSISTENT_DATABASE: Result := sERR_INCONSISTENT_DATABASE;
     ERR_INVALID_COMPARISON: Result := sERR_INVALID_COMPARISON;
     ERR_COMPARISON_FAILED: Result := sERR_COMPARISON_FAILED;
     ERR_TRANSACTIONS_DISABLED: Result := sERR_TRANSACTIONS_DISABLED;
     ERR_INVALID_TRANSPORT: Result := sERR_INVALID_TRANSPORT;
     ERR_SYNTAX_INVALID_IN_NAME: Result := sERR_SYNTAX_INVALID_IN_NAME;
     ERR_REPLICA_ALREADY_EXISTS: Result := sERR_REPLICA_ALREADY_EXISTS;
     ERR_TRANSPORT_FAILURE: Result := sERR_TRANSPORT_FAILURE;
     ERR_ALL_REFERRALS_FAILED: Result := sERR_ALL_REFERRALS_FAILED;
     ERR_CANT_REMOVE_NAMING_VALUE: Result := sERR_CANT_REMOVE_NAMING_VALUE;
     ERR_OBJECT_CLASS_VIOLATION: Result := sERR_OBJECT_CLASS_VIOLATION;
     ERR_ENTRY_IS_NOT_LEAF: Result := sERR_ENTRY_IS_NOT_LEAF;
     ERR_DIFFERENT_TREE: Result := sERR_DIFFERENT_TREE;
     ERR_ILLEGAL_REPLICA_TYPE: Result := sERR_ILLEGAL_REPLICA_TYPE;
     ERR_SYSTEM_FAILURE: Result := sERR_SYSTEM_FAILURE;
     ERR_INVALID_ENTRY_FOR_ROOT: Result := sERR_INVALID_ENTRY_FOR_ROOT;
     ERR_NO_REFERRALS: Result := sERR_NO_REFERRALS;
     ERR_REMOTE_FAILURE: Result := sERR_REMOTE_FAILURE;
     ERR_UNREACHABLE_SERVER: Result := sERR_UNREACHABLE_SERVER;
     ERR_PREVIOUS_MOVE_IN_PROGRESS: Result := sERR_PREVIOUS_MOVE_IN_PROGRESS;
     ERR_NO_CHARACTER_MAPPING: Result := sERR_NO_CHARACTER_MAPPING;
     ERR_INCOMPLETE_AUTHENTICATION: Result := sERR_INCOMPLETE_AUTHENTICATION;
     ERR_INVALID_CERTIFICATE: Result := sERR_INVALID_CERTIFICATE;
     ERR_INVALID_REQUEST: Result := sERR_INVALID_REQUEST;
     ERR_INVALID_ITERATION: Result := sERR_INVALID_ITERATION;
     ERR_SCHEMA_IS_NONREMOVABLE: Result := sERR_SCHEMA_IS_NONREMOVABLE;
     ERR_SCHEMA_IS_IN_USE: Result := sERR_SCHEMA_IS_IN_USE;
     ERR_CLASS_ALREADY_EXISTS: Result := sERR_CLASS_ALREADY_EXISTS;
     ERR_BAD_NAMING_ATTRIBUTES: Result := sERR_BAD_NAMING_ATTRIBUTES;
     ERR_NOT_ROOT_PARTITION: Result := sERR_NOT_ROOT_PARTITION;
     ERR_INSUFFICIENT_STACK: Result := sERR_INSUFFICIENT_STACK;
     ERR_INSUFFICIENT_BUFFER: Result := sERR_INSUFFICIENT_BUFFER;
     ERR_AMBIGUOUS_CONTAINMENT: Result := sERR_AMBIGUOUS_CONTAINMENT;
     ERR_AMBIGUOUS_NAMING: Result := sERR_AMBIGUOUS_NAMING;
     ERR_DUPLICATE_MANDATORY: Result := sERR_DUPLICATE_MANDATORY;
     ERR_DUPLICATE_OPTIONAL: Result := sERR_DUPLICATE_OPTIONAL;
     ERR_PARTITION_BUSY: Result := sERR_PARTITION_BUSY;
     ERR_MULTIPLE_REPLICAS: Result := sERR_MULTIPLE_REPLICAS;
     ERR_CRUCIAL_REPLICA: Result := sERR_CRUCIAL_REPLICA;
     ERR_SCHEMA_SYNC_IN_PROGRESS: Result := sERR_SCHEMA_SYNC_IN_PROGRESS;
     ERR_SKULK_IN_PROGRESS: Result := sERR_SKULK_IN_PROGRESS;
     ERR_TIME_NOT_SYNCHRONIZED: Result := sERR_TIME_NOT_SYNCHRONIZED;
     ERR_RECORD_IN_USE: Result := sERR_RECORD_IN_USE;
     ERR_DS_VOLUME_NOT_MOUNTED: Result := sERR_DS_VOLUME_NOT_MOUNTED;
     ERR_DS_VOLUME_IO_FAILURE: Result := sERR_DS_VOLUME_IO_FAILURE;
     ERR_DS_LOCKED: Result := sERR_DS_LOCKED;
     ERR_OLD_EPOCH: Result := sERR_OLD_EPOCH;
     ERR_NEW_EPOCH: Result := sERR_NEW_EPOCH;
     ERR_INCOMPATIBLE_DS_VERSION: Result := sERR_INCOMPATIBLE_DS_VERSION;
     ERR_PARTITION_ROOT: Result := sERR_PARTITION_ROOT;
     ERR_ENTRY_NOT_CONTAINER: Result := sERR_ENTRY_NOT_CONTAINER;
     ERR_FAILED_AUTHENTICATION: Result := sERR_FAILED_AUTHENTICATION;
     ERR_INVALID_CONTEXT: Result := sERR_INVALID_CONTEXT;
     ERR_NO_SUCH_PARENT: Result := sERR_NO_SUCH_PARENT;
     ERR_NO_ACCESS: Result := sERR_NO_ACCESS;
     ERR_REPLICA_NOT_ON: Result := sERR_REPLICA_NOT_ON;
     ERR_INVALID_NAME_SERVICE: Result := sERR_INVALID_NAME_SERVICE;
     ERR_INVALID_TASK: Result := sERR_INVALID_TASK;
     ERR_INVALID_CONN_HANDLE: Result := sERR_INVALID_CONN_HANDLE;
     ERR_INVALID_IDENTITY: Result := sERR_INVALID_IDENTITY;
     ERR_DUPLICATE_ACL: Result := sERR_DUPLICATE_ACL;
     ERR_PARTITION_ALREADY_EXISTS: Result := sERR_PARTITION_ALREADY_EXISTS;
     ERR_TRANSPORT_MODIFIED: Result := sERR_TRANSPORT_MODIFIED;
     ERR_ALIAS_OF_AN_ALIAS: Result := sERR_ALIAS_OF_AN_ALIAS;
     ERR_AUDITING_FAILED: Result := sERR_AUDITING_FAILED;
     ERR_INVALID_API_VERSION: Result := sERR_INVALID_API_VERSION;
     ERR_SECURE_NCP_VIOLATION: Result := sERR_SECURE_NCP_VIOLATION;
     ERR_MOVE_IN_PROGRESS: Result := sERR_MOVE_IN_PROGRESS;
     ERR_NOT_LEAF_PARTITION: Result := sERR_NOT_LEAF_PARTITION;
     ERR_CANNOT_ABORT: Result := sERR_CANNOT_ABORT;
     ERR_CACHE_OVERFLOW: Result := sERR_CACHE_OVERFLOW;
     ERR_INVALID_SUBORDINATE_COUNT: Result := sERR_INVALID_SUBORDINATE_COUNT;
     ERR_INVALID_RDN: Result := sERR_INVALID_RDN;
     ERR_MOD_TIME_NOT_CURRENT: Result := sERR_MOD_TIME_NOT_CURRENT;
     ERR_INCORRECT_BASE_CLASS: Result := sERR_INCORRECT_BASE_CLASS;
     ERR_MISSING_REFERENCE: Result := sERR_MISSING_REFERENCE;
     ERR_LOST_ENTRY: Result := sERR_LOST_ENTRY;
     ERR_AGENT_ALREADY_REGISTERED: Result := sERR_AGENT_ALREADY_REGISTERED;
     ERR_DS_LOADER_BUSY: Result := sERR_DS_LOADER_BUSY;
     ERR_DS_CANNOT_RELOAD: Result := sERR_DS_CANNOT_RELOAD;
     ERR_REPLICA_IN_SKULK: Result := sERR_REPLICA_IN_SKULK;
     ERR_FATAL: Result := sERR_FATAL;
     ERR_OBSOLETE_API: Result := sERR_OBSOLETE_API;
     ERR_SYNCHRONIZATION_DISABLED: Result := sERR_SYNCHRONIZATION_DISABLED;
     ERR_INVALID_PARAMETER: Result := sERR_INVALID_PARAMETER;
     ERR_DUPLICATE_TEMPLATE: Result := sERR_DUPLICATE_TEMPLATE;
     ERR_NO_MASTER_REPLICA: Result := sERR_NO_MASTER_REPLICA;
     ERR_DUPLICATE_CONTAINMENT: Result := sERR_DUPLICATE_CONTAINMENT;
     ERR_NOT_SIBLING: Result := sERR_NOT_SIBLING;
     ERR_INVALID_SIGNATURE: Result := sERR_INVALID_SIGNATURE;
     ERR_INVALID_RESPONSE: Result := sERR_INVALID_RESPONSE;
     ERR_INSUFFICIENT_SOCKETS: Result := sERR_INSUFFICIENT_SOCKETS;
     ERR_DATABASE_READ_FAIL: Result := sERR_DATABASE_READ_FAIL;
     ERR_INVALID_CODE_PAGE: Result := sERR_INVALID_CODE_PAGE;
     ERR_INVALID_ESCAPE_CHAR: Result := sERR_INVALID_ESCAPE_CHAR;
     ERR_INVALID_DELIMITERS: Result := sERR_INVALID_DELIMITERS;
     ERR_NOT_IMPLEMENTED: Result := sERR_NOT_IMPLEMENTED;
     ERR_CHECKSUM_FAILURE: Result := sERR_CHECKSUM_FAILURE;
     ERR_CHECKSUMMING_NOT_SUPPORTED: Result := sERR_CHECKSUMMING_NOT_SUPPORTED;
     ERR_CRC_FAILURE: Result := sERR_CRC_FAILURE;
  else
    Result := '';
  end;
end;

function SysAndNWCErrorMessage(ErrorCode: Integer): String;
begin
   Result := SysErrorMessage(ErrorCode);
   if Length(Result) = 0 then Result := NWCErrorMessage(ErrorCode);
end;
(*
function CheckNWCError(Res: DWORD): string;
var
   Error: EWin32Error;
   s: string;
begin
   s := '';
   if (Res <> 0{NERR_Success}) {and (Res <> ERROR_MORE_DATA)} then begin
      s := SysAndNWCErrorMessage(0-Res);
      Error := EWin32Error.CreateFmt(sERR_Error, [Res, s]);
      Error.ErrorCode := Res;
//      raise Error;
   end;
   Result := s;
end;
*)
function CheckNWCError(Operation: string; Res: DWORD): string;
var
   s: string;
   Error: EWin32Error;
begin
   Result := '';
   if (Res <> 0{NERR_Success}) {and (Res <> ERROR_MORE_DATA)} then begin
      s := SysAndNWCErrorMessage(0-Res);
      Result := Format(sNWCError, [Operation, Res, s]);
      Error := EWin32Error.CreateFmt(sNWCError, [Operation, Res, s]);
      Error.ErrorCode := Res;
      if (0-Res) <> ERR_BUFFER_EMPTY then
         raise Error;
   end;
end;

end.
