(******************************************************************************

  %name: nwnet.h %
  %version: 3 %
  %date_modified: Wed Dec 18 12:08:56 1996 %
  $Copyright:

  Copyright (c) 1989-1995 Novell, Inc.  All Rights Reserved.                      

  THIS WORK IS  SUBJECT  TO  U.S.  AND  INTERNATIONAL  COPYRIGHT  LAWS  AND
  TREATIES.   NO  PART  OF  THIS  WORK MAY BE  USED,  PRACTICED,  PERFORMED
  COPIED, DISTRIBUTED, REVISED, MODIFIED, TRANSLATED,  ABRIDGED, CONDENSED,
  EXPANDED,  COLLECTED,  COMPILED,  LINKED,  RECAST, TRANSFORMED OR ADAPTED
  WITHOUT THE PRIOR WRITTEN CONSENT OF NOVELL, INC. ANY USE OR EXPLOITATION
  OF THIS WORK WITHOUT AUTHORIZATION COULD SUBJECT THE PERPETRATOR TO
  CRIMINAL AND CIVIL LIABILITY.$

 *****************************************************************************)

{$IFNDEF  NWNET_H }
    {$DEFINE NWNET_H}
    {$IFNDEF  NWDSTYPE_H }
        {$I nwdstype.inc}
    {$ENDIF}
    {$IFNDEF  NWALIAS_H }
        {$I nwalias.inc}
    {$ENDIF}
    {$IFNDEF  NWDSDEFS_H }
        {$I nwdsdefs.inc}
    {$ENDIF}
    {$IFNDEF  NWDSERR_H }
        {$I nwdserr.inc}
    {$ENDIF}
    {$IFNDEF  NWDSNAME_H }
        {$I nwdsname.inc}
    {$ENDIF}
    {$IFNDEF  NWDSFILT_H }
        {$I nwdsfilt.inc}
    {$ENDIF}
    {$IFNDEF  NWDSDC_H }
        {$I nwdsdc.inc}
    {$ENDIF}
    {$IFNDEF  NWDSMISC_H }
        {$I nwdsmisc.inc}
    {$ENDIF}
    {$IFNDEF  NWDSACL_H }
        {$I nwdsacl.inc}
    {$ENDIF}
    {$IFNDEF  NWDSAUD_H }
        {$I nwdsaud.inc}
    {$ENDIF}
    {$IFNDEF  NWDSDSA_H }
        {$I nwdsdsa.inc}
    {$ENDIF}
    {$IFNDEF  NWDSSCH_H }
        {$I nwdssch.inc}
    {$ENDIF}
    {$IFNDEF  NWDSATTR_H }
        {$I nwdsattr.inc}
    {$ENDIF}
    {$IFNDEF  NWDSASA_H }
        {$I nwdsasa.inc}
    {$ENDIF}
    {$IFNDEF  NWDSPART_H }
        {$I nwdspart.inc}
    {$ENDIF}
    {$IFNDEF  NWDSBUFT_H }
        {$I nwdsbuft.inc}
    {$ENDIF}
    {$IFNDEF  NWDSNMTP_H }
        {$I nwdsnmtp.inc}
    {$ENDIF}
    {$IFNDEF  UNICODE_H }
        {$I unicode.inc}
    {$ENDIF}
    {$IFNDEF  NWAUDIT_H }
        {$I nwaudit.inc}
    {$ENDIF}
    {$IFNDEF  NWNDSCON_H }
        {$I nwndscon.inc}
    {$ENDIF}
    {$IFNDEF  NWDSCONN_H }
        {$I nwdsconn.inc}
    {$ENDIF}
{$ENDIF}

