(*
//ษออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออป
//บ (c) 1993 Novell, Inc.	All rights reserved.                              บ
//บ																								  บ
//บ THIS WORK IS SUBJECT TO U.S. AND INTERNATIONAL COPYRIGHT LAWS AND		  บ
//บ TREATIES.																					  บ
//บ																								  บ
//บ NO PART OF THIS WORK MAY BE USED, PRACTICED, PERFORMED, COPIED,			  บ
//บ DISTRIBUTED, REVISED, MODIFIED, TRANSLATED, ABRIDGED, CONDENSED,         บ
//บ EXPANDED, COLLECTED, COMPILED, LINKED, RECAST, TRANSFORMED OR ADAPTED	  บ
//บ WITHOUT THE PRIOR WRITTEN CONSENT OF NOVELL, INC.                        บ
//บ																								  บ
//บ ANY USE OR EXPLOITATION OF THIS WORK WITHOUT AUTHORIZATION COULD SUBJECT บ
//บ THE PERPETRATOR TO CRIMINAL AND CIVIL LIABILITY.								  บ
//ฬออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออน
//บ Source module name: NWPS_NLM.H														  บ
//ศออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผ
*)

{$IFNDEF NWPS_DEF_INC}

{$I nwps_def.inc}
{$ENDIF}


{$IFNDEF NWPS_NLM_INC}

{$DEFINE NWPS_NLM_INC}
(****************************************************************************)

(*************** NLM - NLM Library Special Entry Points *********************)

(****************************************************************************)


(****************************************************************************)

(**  N W P S x x x x x x x x x	C a l l s  *********************************)

(****************************************************************************)


{$IFDEF __cplusplus}

(* TC extern C *)
{$ENDIF}


(*++++++++++++ Register and DeRegister a Client ++++++++++++++++++++++++++++*)

(* TC  int NWPSRegisterLibraryClient ( void );  *)


(* TC  int NWPSDeRegisterLibraryClient ( void );  *)


{$IFDEF __cplusplus}

(* TC } *)
{$ENDIF}


{$ENDIF}


